# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'UI_Day3.2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UI_Day3.2
pod 'SDWebImage', '~> 5.0'
pod 'Alamofire', '~> 5.5'

end
